const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const sizes=p=>p.sizes||(p.category==='Sneakers'?['42','43','44','45']:['S','M','L','XL']);
function media(p,context='card'){
  const original=p.packshot||p.photo||p.reference;
  const src=original?`../${original}`:null;
  const set=p.packshotSet||p.photoSet;
  const srcset=set?set.split(',').map(part=>`../${part.trim()}`).join(', '):'';
  const sizes=context==='thumb'?'82px':context==='detail'?'(max-width:680px) 100vw, 50vw':'(max-width:680px) 50vw, (max-width:1000px) 33vw, 25vw';
  const color=/^#[0-9a-f]{6}$/i.test(p.color||'')?p.color:'#8b8b84';
  const placeholder=`<div class="placeholder" style="--piece-color:${color}" ${src?'hidden':''}><div class="placeholder-mark" aria-hidden="true">M1</div><div class="placeholder-meta"><strong>${p.brand}</strong><span>${p.name}</span><small>IMAGE UNAVAILABLE</small></div></div>`;
  const dimensions=`width="${p.imageWidth||960}" height="${p.imageHeight||1280}"`;
  return src?`<img class="${p.packshot?'packshot':p.photo?'session-photo':'reference-photo'}" src="${src}" ${srcset?`srcset="${srcset}" sizes="${sizes}"`:''} ${dimensions} alt="${p.packshot?'MIESHKO GOAT piece:':p.photo?'MIESHKO wearing':'Piece:'} ${p.brand} ${p.name}" loading="${context==='detail'?'eager':'lazy'}" decoding="async" onerror="this.hidden=true;this.nextElementSibling.hidden=false">${placeholder}`:placeholder;
}
let cartItems=[];try{cartItems=JSON.parse(localStorage.getItem('mieszko-set')||'[]').filter(x=>x&&products.some(p=>p.id===x.id)&&sizes(products.find(p=>p.id===x.id)).includes(x.size)).map(x=>({...x,qty:Math.min(9,Math.max(1,Number(x.qty)||1))}));}catch{}
const detail=$('#detail'),cart=$('#cart');let currentCollection='goat',currentFilter='all',searchTerm='',sortOrder='curated',selectedSize=null;
function render(){let list=products.filter(p=>(p.collection||'archive')===currentCollection&&(currentFilter==='all'||p.category===currentFilter)&&`${p.brand} ${p.name} ${p.edition} ${p.year} ${p.category}`.toLowerCase().includes(searchTerm.toLowerCase().trim()));if(sortOrder==='new')list.sort((a,b)=>b.year-a.year);if(sortOrder==='old')list.sort((a,b)=>a.year-b.year);if(sortOrder==='name')list.sort((a,b)=>a.name.localeCompare(b.name));$('#resultCount').textContent=`${list.length} pieces`;$('#grid').innerHTML=list.length?list.map(p=>`<button class="product" data-product="${p.id}"><div class="product-art">${media(p)}</div><div class="product-info"><span>${p.brand}</span><h3>${p.name}</h3><p>${p.edition}</p><div class="card-sizes">${sizes(p).join(' ')}</div></div></button>`).join(''):`<div class="empty-results">No pieces found.<br><button id="resetSearch">Show the full collection</button></div>`;$$('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product));if($('#resetSearch'))$('#resetSearch').onclick=()=>{searchTerm='';$('#search').value='';setCategory('all')};}
function closeMobileMenu(){$('#mobileMenu').hidden=true;$('#menuButton').setAttribute('aria-expanded','false')}
function setCategory(c){currentFilter=c;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===c));closeMobileMenu();render();}
function setCollection(c){const lookbook=$('#goatLookbook');if(lookbook)lookbook.hidden=c!=='goat';currentCollection=c==='goat'?'goat':'archive';searchTerm='';$('#search').value='';$$('[data-collection]').forEach(b=>{const active=b.dataset.collection===currentCollection;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});$('#collectionTitle').textContent=currentCollection==='goat'?'MIESHKO GOAT':'Archive';$('#collectionDescription').textContent=currentCollection==='goat'?'Drop 01. Ten original pieces. One of one.':'23 selected archive looks. 1985 — 2026.';$('#photoNote').textContent=currentCollection==='goat'?'DROP 01 / ONE OF ONE / MIESHKO GOAT':'ARCHIVE / 23 SELECTED LOOKS';$$('[data-filter]').forEach(b=>b.hidden=b.dataset.filter!=='all'&&!products.some(p=>(p.collection||'archive')===currentCollection&&p.category===b.dataset.filter));setCategory('all');}
function showProduct(id){const p=products.find(p=>p.id===id);selectedSize=null;$('#detailBody').innerHTML=`<div class="detail-art">${media(p,'detail')}<small>${p.packshot?'MIESHKO GOAT / DROP 01':'MIESHKO / ARCHIVE'}</small></div><div class="detail-copy"><span class="brand">${p.brand}</span><h2>${p.name}</h2><p class="edition">${p.edition}</p><div class="product-status">Showcase edition · not for sale</div><div class="size-header"><span>Select a size</span><button id="sizeGuide">Size guide</button></div><div class="size-options" role="group" aria-label="Select a size">${sizes(p).map(s=>`<button data-size="${s}" aria-pressed="false">${s}</button>`).join('')}</div><p id="sizeError" class="size-error" role="status" hidden>Select a size to add this piece.</p><button class="primary" id="add">Add to bag</button><p class="small">A virtual bag. No order will be placed.</p><details open><summary>About this piece</summary><p>${p.why}</p></details><details><summary>Edition details</summary><p>${p.brand}<br>${p.edition}<br>${p.collection==='goat'?'Collection year':'Archive year'}: ${p.year}. Sizes are for this showcase only and do not indicate availability.</p></details>${p.source?`<a class="source" href="${p.source}" target="_blank" rel="noopener noreferrer">Edition reference</a>`:''}</div>`;$$('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;$$('[data-size]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});$('#sizeError').hidden=true;});$('#sizeGuide').onclick=()=>showInfo('sizes');$('#add').onclick=()=>{if(!selectedSize){$('#sizeError').hidden=false;return}const existing=cartItems.find(x=>x.id===id&&x.size===selectedSize);if(existing)existing.qty=Math.min(9,existing.qty+1);else cartItems.push({id,size:selectedSize,qty:1});save();detail.close();showCart();toast('Added to bag');};detail.showModal();}
function save(){try{localStorage.setItem('mieszko-set',JSON.stringify(cartItems));}catch{}$('#count').textContent=cartItems.reduce((n,x)=>n+x.qty,0);}
function changeQty(index,delta){const x=cartItems[index];x.qty=Math.max(0,Math.min(9,x.qty+delta));if(!x.qty)cartItems.splice(index,1);save();showCart();}
function showCart(){const count=cartItems.reduce((n,x)=>n+x.qty,0);$('#cartBody').innerHTML=`<h2>Bag (${count})</h2>${cartItems.length?`<div class="cart-items">${cartItems.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-row"><div class="cart-thumb">${media(p,'thumb')}</div><section><span class="brand">${p.brand}</span><h3>${p.name}</h3><p>${p.edition}</p><p>Size: ${x.size}</p><div class="quantity"><button data-qty="${i}" data-delta="-1" aria-label="Decrease quantity of ${p.name}">−</button><span>${x.qty}</span><button data-qty="${i}" data-delta="1" aria-label="Increase quantity of ${p.name}" ${x.qty===9?'disabled':''}>+</button></div><button class="remove" data-remove="${i}">Remove</button></section></div>`}).join('')}</div><div class="total"><span>Total</span><span>A birthday gift</span></div><p class="cart-note">A private birthday showcase for MIESHKO. No charges, orders or delivery.</p><button class="primary" id="finish">Open birthday message</button><button class="continue" id="continueShopping">Keep browsing</button>`:'<p class="empty">Your bag is empty.</p><button class="primary" id="browse">Keep browsing</button>'}`;$$('[data-remove]').forEach(b=>b.onclick=()=>{cartItems.splice(Number(b.dataset.remove),1);save();showCart()});$$('[data-qty]').forEach(b=>b.onclick=()=>changeQty(Number(b.dataset.qty),Number(b.dataset.delta)));if($('#finish'))$('#finish').onclick=celebrate;['#browse','#continueShopping'].forEach(s=>{if($(s))$(s).onclick=()=>cart.close()});if(!cart.open)cart.showModal();}
function celebrate(){const count=cartItems.reduce((n,x)=>n+x.qty,0);$('#cartBody').innerHTML=`<div class="birthday"><span class="logo">MIESHKO</span><h2>Happy birthday,<br>MIESHKO.</h2><p>This collection has one person at its centre.<br>His next chapter starts here.</p><strong>Your style. Your rules.</strong><button class="primary" id="back">Back to the collection</button><p class="small">${count} pieces in your virtual bag. No order or payment.</p></div>`;$('#back').onclick=()=>cart.close();for(let i=0;i<35;i++){const c=document.createElement('i');c.className='confetti';c.style.cssText=`left:${Math.random()*100}%;background:${['#161616','#b8b8b8','#d5cbb8'][i%3]};animation-delay:${Math.random()*.7}s`;cart.append(c);setTimeout(()=>c.remove(),3500);}}
const infoContent={about:['About MIESHKO','MIESHKO is a private birthday showcase made for MIESHKO. The archive features selected releases by other labels. This is not an official store or a collaboration with those labels.'],sizes:['Size guide','Clothing: S, M, L, XL. Socks: 39–42 or 43–46. Footwear: EU 42, 43, 44, 45. Sizes serve the virtual bag only. Archival fits vary between labels, and no specific item has been measured.'],demo:['Orders & delivery','This is a private birthday showcase. The bag is part of the gift: there are no payments, orders, reservations or deliveries. Open birthday message to see MIESHKO’s greeting.']};
function showInfo(key){const [title,copy]=infoContent[key];$('#infoBody').innerHTML=`<h2>${title}</h2><p>${copy}</p>`;$('#info').showModal();}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2000)}
$$('[data-collection]').forEach(b=>b.onclick=()=>{setCollection(b.dataset.collection);$('#collection').scrollIntoView({behavior:'smooth'});if(typeof history!=='undefined')history.replaceState(null,'',b.dataset.collection==='goat'?'#mieshko-goat':'#archive')});$$('[data-filter]').forEach(b=>b.onclick=()=>setCategory(b.dataset.filter));$$('[data-category]').forEach(b=>b.onclick=()=>{setCategory(b.dataset.category);$('#catalog').scrollIntoView({behavior:'smooth'})});$$('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info));$$('#mobileMenu a').forEach(a=>a.addEventListener('click',closeMobileMenu));$$('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());[detail,cart,$('#info')].forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$('#cartButton').onclick=showCart;$('#searchButton').onclick=()=>{$('#searchPanel').hidden=!$('#searchPanel').hidden;if(!$('#searchPanel').hidden){$('#catalog').scrollIntoView({behavior:'smooth'});$('#search').focus()}};$('#search').oninput=e=>{searchTerm=e.target.value;render()};$('#clearSearch').onclick=()=>{searchTerm='';$('#search').value='';render()};$('#sort').onchange=e=>{sortOrder=e.target.value;render()};$('#menuButton').onclick=()=>{const menu=$('#mobileMenu');menu.hidden=!menu.hidden;$('#menuButton').setAttribute('aria-expanded',String(!menu.hidden))};save();setCollection(typeof location!=='undefined'&&location.hash==='#archive'?'archive':'goat');if(typeof window!=='undefined')window.addEventListener('hashchange',()=>setCollection(location.hash==='#archive'?'archive':'goat'));
